# Generated by Django 5.1.4 on 2024-12-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hello', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
